import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import Content from '../components/Content'
import Footer from '../components/Footer'

const Home: NextPage = () => {

  return (
    <div  >
      <Head>
        <title >Jin's Porfolio Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    


      <Navbar />
      <Content  />
      <Footer />
        


    </div>
  )
}

export default Home
